/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import HelloWorldResponse from '../models/HelloWorldResponse';

/**
* Root service.
* @module api/RootApi
* @version 0.1.0
*/
export default class RootApi {

    /**
    * Constructs a new RootApi. 
    * @alias module:api/RootApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the readRootGet operation.
     * @callback module:api/RootApi~readRootGetCallback
     * @param {String} error Error message, if any.
     * @param {module:models/HelloWorldResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Read Root
     * @param {module:api/RootApi~readRootGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:models/HelloWorldResponse}
     */
    readRootGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = HelloWorldResponse;
      return this.apiClient.callApi(
        '/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
