FROM node:22.15.1-bullseye-slim AS development

RUN sed -i 's|http://deb.debian.org/debian|http://ftp.de.debian.org/debian|g' /etc/apt/sources.list && \
    apt-get update && \
    apt-get install -y --no-install-recommends curl default-jre-headless

WORKDIR /app

COPY package*.json ./
RUN npm ci

EXPOSE 3000
