/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import HTTPValidationError from './models/HTTPValidationError';
import HelloWorldResponse from './models/HelloWorldResponse';
import SectorCreate from './models/SectorCreate';
import SectorResponse from './models/SectorResponse';
import SectorStatus from './models/SectorStatus';
import UserResponse from './models/UserResponse';
import UserRole from './models/UserRole';
import UserStatus from './models/UserStatus';
import ValidationError from './models/ValidationError';
import ValidationErrorLocInner from './models/ValidationErrorLocInner';
import RootApi from './api/RootApi';
import SectorsApi from './api/SectorsApi';
import UsersApi from './api/UsersApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var FastApi = require('index'); // See note below*.
* var xxxSvc = new FastApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new FastApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new FastApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new FastApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The HTTPValidationError model constructor.
     * @property {module:models/HTTPValidationError}
     */
    HTTPValidationError,

    /**
     * The HelloWorldResponse model constructor.
     * @property {module:models/HelloWorldResponse}
     */
    HelloWorldResponse,

    /**
     * The SectorCreate model constructor.
     * @property {module:models/SectorCreate}
     */
    SectorCreate,

    /**
     * The SectorResponse model constructor.
     * @property {module:models/SectorResponse}
     */
    SectorResponse,

    /**
     * The SectorStatus model constructor.
     * @property {module:models/SectorStatus}
     */
    SectorStatus,

    /**
     * The UserResponse model constructor.
     * @property {module:models/UserResponse}
     */
    UserResponse,

    /**
     * The UserRole model constructor.
     * @property {module:models/UserRole}
     */
    UserRole,

    /**
     * The UserStatus model constructor.
     * @property {module:models/UserStatus}
     */
    UserStatus,

    /**
     * The ValidationError model constructor.
     * @property {module:models/ValidationError}
     */
    ValidationError,

    /**
     * The ValidationErrorLocInner model constructor.
     * @property {module:models/ValidationErrorLocInner}
     */
    ValidationErrorLocInner,

    /**
    * The RootApi service constructor.
    * @property {module:api/RootApi}
    */
    RootApi,

    /**
    * The SectorsApi service constructor.
    * @property {module:api/SectorsApi}
    */
    SectorsApi,

    /**
    * The UsersApi service constructor.
    * @property {module:api/UsersApi}
    */
    UsersApi
};
