/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FastApi);
  }
}(this, function(expect, FastApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FastApi.SectorsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SectorsApi', function() {
    describe('assignSectorToNgoSectorsSectorIdAssignNgoNgoIdPut', function() {
      it('should call assignSectorToNgoSectorsSectorIdAssignNgoNgoIdPut successfully', function(done) {
        //uncomment below and update the code to test assignSectorToNgoSectorsSectorIdAssignNgoNgoIdPut
        //instance.assignSectorToNgoSectorsSectorIdAssignNgoNgoIdPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('assignSectorToOperatorSectorsSectorIdAssignOperatorOperatorIdPut', function() {
      it('should call assignSectorToOperatorSectorsSectorIdAssignOperatorOperatorIdPut successfully', function(done) {
        //uncomment below and update the code to test assignSectorToOperatorSectorsSectorIdAssignOperatorOperatorIdPut
        //instance.assignSectorToOperatorSectorsSectorIdAssignOperatorOperatorIdPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('assignSectorToTeamLeadSectorsSectorIdAssignTeamLeadTeamLeadIdPut', function() {
      it('should call assignSectorToTeamLeadSectorsSectorIdAssignTeamLeadTeamLeadIdPut successfully', function(done) {
        //uncomment below and update the code to test assignSectorToTeamLeadSectorsSectorIdAssignTeamLeadTeamLeadIdPut
        //instance.assignSectorToTeamLeadSectorsSectorIdAssignTeamLeadTeamLeadIdPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createSectorSectorsPost', function() {
      it('should call createSectorSectorsPost successfully', function(done) {
        //uncomment below and update the code to test createSectorSectorsPost
        //instance.createSectorSectorsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteSectorSectorsSectorIdDelete', function() {
      it('should call deleteSectorSectorsSectorIdDelete successfully', function(done) {
        //uncomment below and update the code to test deleteSectorSectorsSectorIdDelete
        //instance.deleteSectorSectorsSectorIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllSectorsSectorsGet', function() {
      it('should call getAllSectorsSectorsGet successfully', function(done) {
        //uncomment below and update the code to test getAllSectorsSectorsGet
        //instance.getAllSectorsSectorsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCompletelyUnassignedSectorsSectorsUnassignedAllGet', function() {
      it('should call getCompletelyUnassignedSectorsSectorsUnassignedAllGet successfully', function(done) {
        //uncomment below and update the code to test getCompletelyUnassignedSectorsSectorsUnassignedAllGet
        //instance.getCompletelyUnassignedSectorsSectorsUnassignedAllGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSectorByIdSectorsSectorIdGet', function() {
      it('should call getSectorByIdSectorsSectorIdGet successfully', function(done) {
        //uncomment below and update the code to test getSectorByIdSectorsSectorIdGet
        //instance.getSectorByIdSectorsSectorIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSectorsByNgoSectorsNgoNgoIdGet', function() {
      it('should call getSectorsByNgoSectorsNgoNgoIdGet successfully', function(done) {
        //uncomment below and update the code to test getSectorsByNgoSectorsNgoNgoIdGet
        //instance.getSectorsByNgoSectorsNgoNgoIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSectorsByOperatorSectorsOperatorOperatorIdGet', function() {
      it('should call getSectorsByOperatorSectorsOperatorOperatorIdGet successfully', function(done) {
        //uncomment below and update the code to test getSectorsByOperatorSectorsOperatorOperatorIdGet
        //instance.getSectorsByOperatorSectorsOperatorOperatorIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSectorsByStatusSectorsStatusStatusGet', function() {
      it('should call getSectorsByStatusSectorsStatusStatusGet successfully', function(done) {
        //uncomment below and update the code to test getSectorsByStatusSectorsStatusStatusGet
        //instance.getSectorsByStatusSectorsStatusStatusGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSectorsByTeamLeadSectorsTeamLeadTeamLeadIdGet', function() {
      it('should call getSectorsByTeamLeadSectorsTeamLeadTeamLeadIdGet successfully', function(done) {
        //uncomment below and update the code to test getSectorsByTeamLeadSectorsTeamLeadTeamLeadIdGet
        //instance.getSectorsByTeamLeadSectorsTeamLeadTeamLeadIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSectorsWithAssignmentsSectorsWithAssignmentsGet', function() {
      it('should call getSectorsWithAssignmentsSectorsWithAssignmentsGet successfully', function(done) {
        //uncomment below and update the code to test getSectorsWithAssignmentsSectorsWithAssignmentsGet
        //instance.getSectorsWithAssignmentsSectorsWithAssignmentsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUnassignedNgoSectorsSectorsUnassignedNgoGet', function() {
      it('should call getUnassignedNgoSectorsSectorsUnassignedNgoGet successfully', function(done) {
        //uncomment below and update the code to test getUnassignedNgoSectorsSectorsUnassignedNgoGet
        //instance.getUnassignedNgoSectorsSectorsUnassignedNgoGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUnassignedOperatorSectorsSectorsUnassignedOperatorGet', function() {
      it('should call getUnassignedOperatorSectorsSectorsUnassignedOperatorGet successfully', function(done) {
        //uncomment below and update the code to test getUnassignedOperatorSectorsSectorsUnassignedOperatorGet
        //instance.getUnassignedOperatorSectorsSectorsUnassignedOperatorGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUnassignedTeamLeadSectorsSectorsUnassignedTeamLeadGet', function() {
      it('should call getUnassignedTeamLeadSectorsSectorsUnassignedTeamLeadGet successfully', function(done) {
        //uncomment below and update the code to test getUnassignedTeamLeadSectorsSectorsUnassignedTeamLeadGet
        //instance.getUnassignedTeamLeadSectorsSectorsUnassignedTeamLeadGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateSectorStatusSectorsSectorIdStatusStatusPut', function() {
      it('should call updateSectorStatusSectorsSectorIdStatusStatusPut successfully', function(done) {
        //uncomment below and update the code to test updateSectorStatusSectorsSectorIdStatusStatusPut
        //instance.updateSectorStatusSectorsSectorIdStatusStatusPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
