/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FastApi);
  }
}(this, function(expect, FastApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FastApi.UsersApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UsersApi', function() {
    describe('getActiveUsersUsersActiveAllGet', function() {
      it('should call getActiveUsersUsersActiveAllGet successfully', function(done) {
        //uncomment below and update the code to test getActiveUsersUsersActiveAllGet
        //instance.getActiveUsersUsersActiveAllGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllUsersUsersGet', function() {
      it('should call getAllUsersUsersGet successfully', function(done) {
        //uncomment below and update the code to test getAllUsersUsersGet
        //instance.getAllUsersUsersGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getInactiveUsersUsersInactiveAllGet', function() {
      it('should call getInactiveUsersUsersInactiveAllGet successfully', function(done) {
        //uncomment below and update the code to test getInactiveUsersUsersInactiveAllGet
        //instance.getInactiveUsersUsersInactiveAllGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getNgosUsersNgosAllGet', function() {
      it('should call getNgosUsersNgosAllGet successfully', function(done) {
        //uncomment below and update the code to test getNgosUsersNgosAllGet
        //instance.getNgosUsersNgosAllGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getOperatorsUsersOperatorsAllGet', function() {
      it('should call getOperatorsUsersOperatorsAllGet successfully', function(done) {
        //uncomment below and update the code to test getOperatorsUsersOperatorsAllGet
        //instance.getOperatorsUsersOperatorsAllGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTeamLeadsUsersTeamLeadsAllGet', function() {
      it('should call getTeamLeadsUsersTeamLeadsAllGet successfully', function(done) {
        //uncomment below and update the code to test getTeamLeadsUsersTeamLeadsAllGet
        //instance.getTeamLeadsUsersTeamLeadsAllGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserByIdUsersUserIdGet', function() {
      it('should call getUserByIdUsersUserIdGet successfully', function(done) {
        //uncomment below and update the code to test getUserByIdUsersUserIdGet
        //instance.getUserByIdUsersUserIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserByUsernameUsersUsernameUsernameGet', function() {
      it('should call getUserByUsernameUsersUsernameUsernameGet successfully', function(done) {
        //uncomment below and update the code to test getUserByUsernameUsersUsernameUsernameGet
        //instance.getUserByUsernameUsersUsernameUsernameGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUsersByParentUsersParentParentUserIdGet', function() {
      it('should call getUsersByParentUsersParentParentUserIdGet successfully', function(done) {
        //uncomment below and update the code to test getUsersByParentUsersParentParentUserIdGet
        //instance.getUsersByParentUsersParentParentUserIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUsersByRoleUsersRoleRoleGet', function() {
      it('should call getUsersByRoleUsersRoleRoleGet successfully', function(done) {
        //uncomment below and update the code to test getUsersByRoleUsersRoleRoleGet
        //instance.getUsersByRoleUsersRoleRoleGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUsersByStatusUsersStatusStatusGet', function() {
      it('should call getUsersByStatusUsersStatusStatusGet successfully', function(done) {
        //uncomment below and update the code to test getUsersByStatusUsersStatusStatusGet
        //instance.getUsersByStatusUsersStatusStatusGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
