/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SectorStatus from './SectorStatus';
import UserResponse from './UserResponse';

/**
 * The SectorResponse model module.
 * @module models/SectorResponse
 * @version 0.1.0
 */
class SectorResponse {
    /**
     * Constructs a new <code>SectorResponse</code>.
     * DTO for returning sector information, including nested user details.
     * @alias module:models/SectorResponse
     * @param id {String} 
     * @param geometry {Object.<String, Object>} 
     * @param areaSqm {Number} 
     * @param riskProbability {Number} 
     * @param totalMinesFound {Number} 
     * @param status {module:models/SectorStatus} 
     * @param createdAt {Date} 
     */
    constructor(id, geometry, areaSqm, riskProbability, totalMinesFound, status, createdAt) { 
        
        SectorResponse.initialize(this, id, geometry, areaSqm, riskProbability, totalMinesFound, status, createdAt);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, geometry, areaSqm, riskProbability, totalMinesFound, status, createdAt) { 
        obj['id'] = id;
        obj['geometry'] = geometry;
        obj['area_sqm'] = areaSqm;
        obj['risk_probability'] = riskProbability;
        obj['total_mines_found'] = totalMinesFound;
        obj['status'] = status;
        obj['created_at'] = createdAt;
    }

    /**
     * Constructs a <code>SectorResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:models/SectorResponse} obj Optional instance to populate.
     * @return {module:models/SectorResponse} The populated <code>SectorResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SectorResponse();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('geometry')) {
                obj['geometry'] = ApiClient.convertToType(data['geometry'], {'String': Object});
            }
            if (data.hasOwnProperty('area_sqm')) {
                obj['area_sqm'] = ApiClient.convertToType(data['area_sqm'], 'Number');
            }
            if (data.hasOwnProperty('risk_probability')) {
                obj['risk_probability'] = ApiClient.convertToType(data['risk_probability'], 'Number');
            }
            if (data.hasOwnProperty('total_mines_found')) {
                obj['total_mines_found'] = ApiClient.convertToType(data['total_mines_found'], 'Number');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = SectorStatus.constructFromObject(data['status']);
            }
            if (data.hasOwnProperty('created_at')) {
                obj['created_at'] = ApiClient.convertToType(data['created_at'], 'Date');
            }
            if (data.hasOwnProperty('updated_at')) {
                obj['updated_at'] = ApiClient.convertToType(data['updated_at'], 'Date');
            }
            if (data.hasOwnProperty('assigned_ngo')) {
                obj['assigned_ngo'] = UserResponse.constructFromObject(data['assigned_ngo']);
            }
            if (data.hasOwnProperty('assigned_team_lead')) {
                obj['assigned_team_lead'] = UserResponse.constructFromObject(data['assigned_team_lead']);
            }
            if (data.hasOwnProperty('assigned_operator')) {
                obj['assigned_operator'] = UserResponse.constructFromObject(data['assigned_operator']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SectorResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SectorResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SectorResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // validate the optional field `assigned_ngo`
        if (data['assigned_ngo']) { // data not null
          UserResponse.validateJSON(data['assigned_ngo']);
        }
        // validate the optional field `assigned_team_lead`
        if (data['assigned_team_lead']) { // data not null
          UserResponse.validateJSON(data['assigned_team_lead']);
        }
        // validate the optional field `assigned_operator`
        if (data['assigned_operator']) { // data not null
          UserResponse.validateJSON(data['assigned_operator']);
        }

        return true;
    }


}

SectorResponse.RequiredProperties = ["id", "geometry", "area_sqm", "risk_probability", "total_mines_found", "status", "created_at"];

/**
 * @member {String} id
 */
SectorResponse.prototype['id'] = undefined;

/**
 * @member {Object.<String, Object>} geometry
 */
SectorResponse.prototype['geometry'] = undefined;

/**
 * @member {Number} area_sqm
 */
SectorResponse.prototype['area_sqm'] = undefined;

/**
 * @member {Number} risk_probability
 */
SectorResponse.prototype['risk_probability'] = undefined;

/**
 * @member {Number} total_mines_found
 */
SectorResponse.prototype['total_mines_found'] = undefined;

/**
 * @member {module:models/SectorStatus} status
 */
SectorResponse.prototype['status'] = undefined;

/**
 * @member {Date} created_at
 */
SectorResponse.prototype['created_at'] = undefined;

/**
 * @member {Date} updated_at
 */
SectorResponse.prototype['updated_at'] = undefined;

/**
 * @member {module:models/UserResponse} assigned_ngo
 */
SectorResponse.prototype['assigned_ngo'] = undefined;

/**
 * @member {module:models/UserResponse} assigned_team_lead
 */
SectorResponse.prototype['assigned_team_lead'] = undefined;

/**
 * @member {module:models/UserResponse} assigned_operator
 */
SectorResponse.prototype['assigned_operator'] = undefined;






export default SectorResponse;

