/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class SectorStatus.
* @enum {}
* @readonly
*/
export default class SectorStatus {
    
        /**
         * value: "mined"
         * @const
         */
        "mined" = "mined";

    
        /**
         * value: "demined"
         * @const
         */
        "demined" = "demined";

    
        /**
         * value: "clear"
         * @const
         */
        "clear" = "clear";

    
        /**
         * value: "probable"
         * @const
         */
        "probable" = "probable";

    

    /**
    * Returns a <code>SectorStatus</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:models/SectorStatus} The enum <code>SectorStatus</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

