/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class UserRole.
* @enum {}
* @readonly
*/
export default class UserRole {
    
        /**
         * value: "operator"
         * @const
         */
        "operator" = "operator";

    
        /**
         * value: "Team-Lead"
         * @const
         */
        "Team-Lead" = "Team-Lead";

    
        /**
         * value: "ngo"
         * @const
         */
        "ngo" = "ngo";

    
        /**
         * value: "ministry"
         * @const
         */
        "ministry" = "ministry";

    

    /**
    * Returns a <code>UserRole</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:models/UserRole} The enum <code>UserRole</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

