/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SectorStatus } from './sector-status';

/**
 * DTO for creating a new sector. The geometry should be a valid GeoJSON Polygon.
 * @export
 * @interface SectorCreate
 */
export interface SectorCreate {
    /**
     * A GeoJSON object representing the sector\'s polygon.
     * @type {{ [key: string]: any; }}
     * @memberof SectorCreate
     */
    'geometry': { [key: string]: any; };
    /**
     * 
     * @type {SectorStatus}
     * @memberof SectorCreate
     */
    'status'?: SectorStatus | null;
    /**
     * 
     * @type {number}
     * @memberof SectorCreate
     */
    'risk_probability'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof SectorCreate
     */
    'assigned_to_ngo_id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SectorCreate
     */
    'assigned_to_team_lead_id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SectorCreate
     */
    'assigned_to_operator_id'?: string | null;
}



