/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SectorStatus } from './sector-status';
// May contain unused imports in some cases
// @ts-ignore
import type { UserResponse } from './user-response';

/**
 * DTO for returning sector information, including nested user details.
 * @export
 * @interface SectorResponse
 */
export interface SectorResponse {
    /**
     * 
     * @type {string}
     * @memberof SectorResponse
     */
    'id': string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof SectorResponse
     */
    'geometry': { [key: string]: any; };
    /**
     * 
     * @type {number}
     * @memberof SectorResponse
     */
    'area_sqm': number;
    /**
     * 
     * @type {number}
     * @memberof SectorResponse
     */
    'risk_probability': number;
    /**
     * 
     * @type {number}
     * @memberof SectorResponse
     */
    'total_mines_found': number;
    /**
     * 
     * @type {SectorStatus}
     * @memberof SectorResponse
     */
    'status': SectorStatus;
    /**
     * 
     * @type {string}
     * @memberof SectorResponse
     */
    'created_at': string;
    /**
     * 
     * @type {string}
     * @memberof SectorResponse
     */
    'updated_at'?: string | null;
    /**
     * 
     * @type {UserResponse}
     * @memberof SectorResponse
     */
    'assigned_ngo'?: UserResponse | null;
    /**
     * 
     * @type {UserResponse}
     * @memberof SectorResponse
     */
    'assigned_team_lead'?: UserResponse | null;
    /**
     * 
     * @type {UserResponse}
     * @memberof SectorResponse
     */
    'assigned_operator'?: UserResponse | null;
}



