/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UserRole } from './user-role';
// May contain unused imports in some cases
// @ts-ignore
import type { UserStatus } from './user-status';

/**
 * DTO for returning user information.
 * @export
 * @interface UserResponse
 */
export interface UserResponse {
    /**
     * 
     * @type {string}
     * @memberof UserResponse
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof UserResponse
     */
    'userName'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserResponse
     */
    'email'?: string | null;
    /**
     * 
     * @type {UserRole}
     * @memberof UserResponse
     */
    'role': UserRole;
    /**
     * 
     * @type {UserStatus}
     * @memberof UserResponse
     */
    'status': UserStatus;
    /**
     * 
     * @type {string}
     * @memberof UserResponse
     */
    'parent_user_id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserResponse
     */
    'created_at': string;
    /**
     * 
     * @type {string}
     * @memberof UserResponse
     */
    'updated_at'?: string | null;
}



