/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FastApi);
  }
}(this, function(expect, FastApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FastApi.SectorCreate();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SectorCreate', function() {
    it('should create an instance of SectorCreate', function() {
      // uncomment below and update the code to test SectorCreate
      //var instance = new FastApi.SectorCreate();
      //expect(instance).to.be.a(FastApi.SectorCreate);
    });

    it('should have the property geometry (base name: "geometry")', function() {
      // uncomment below and update the code to test the property geometry
      //var instance = new FastApi.SectorCreate();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new FastApi.SectorCreate();
      //expect(instance).to.be();
    });

    it('should have the property riskProbability (base name: "risk_probability")', function() {
      // uncomment below and update the code to test the property riskProbability
      //var instance = new FastApi.SectorCreate();
      //expect(instance).to.be();
    });

    it('should have the property assignedToNgoId (base name: "assigned_to_ngo_id")', function() {
      // uncomment below and update the code to test the property assignedToNgoId
      //var instance = new FastApi.SectorCreate();
      //expect(instance).to.be();
    });

    it('should have the property assignedToTeamLeadId (base name: "assigned_to_team_lead_id")', function() {
      // uncomment below and update the code to test the property assignedToTeamLeadId
      //var instance = new FastApi.SectorCreate();
      //expect(instance).to.be();
    });

    it('should have the property assignedToOperatorId (base name: "assigned_to_operator_id")', function() {
      // uncomment below and update the code to test the property assignedToOperatorId
      //var instance = new FastApi.SectorCreate();
      //expect(instance).to.be();
    });

  });

}));
